<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVZ8mB0c\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVZ8mB0c/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVZ8mB0c.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVZ8mB0c\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVZ8mB0c\App_KernelDevDebugContainer([
    'container.build_hash' => 'VZ8mB0c',
    'container.build_id' => '5d0f0713',
    'container.build_time' => 1633096652,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVZ8mB0c');
